# Generated by Django 3.1 on 2022-01-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('from_star', models.CharField(max_length=30)),
                ('image', models.FilePathField(verbose_name='/img')),
            ],
        ),
    ]
